before_install:
  - "echo '--colour' > ~/.rspec"
  - "echo 'gem: --no-document' > ~/.gemrc"
  - git config --global user.name 'Travis CI'
  - git config --global user.email 'travis-ci@example.com'
before_script:
  - pushd spec/dummy && bundle exec rake db:create && mkdir db/views && popd
branches:
  only:
    - master
language:
  - ruby
notifications:
  email:
    - false
rvm:
  - 2.1.7
  - 2.2.3
sudo: false
